//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftagdetail
    {
        public int Id { get; set; }
        public string ftagname { get; set; }
        public string url { get; set; }
        public string username { get; set; }
        public string virtualname { get; set; }
        public string name { get; set; }
    }
}
