//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.addresses = new HashSet<address>();
            this.addressLabels = new HashSet<addressLabel>();
            this.contacts = new HashSet<contact1>();
            this.dateLabels = new HashSet<dateLabel>();
            this.dates = new HashSet<date>();
            this.emails = new HashSet<email>();
            this.emailLabels = new HashSet<emailLabel>();
            this.fTagDetails = new HashSet<fTagDetail1>();
            this.mobileNoes = new HashSet<mobileNo>();
            this.mobileNoLabels = new HashSet<mobileNoLabel>();
            this.relativeNames = new HashSet<relativeName>();
            this.relativeNameLabels = new HashSet<relativeNameLabel>();
            this.socialProfiles = new HashSet<socialProfile>();
            this.socialProfileLabels = new HashSet<socialProfileLabel>();
            this.urlLabels = new HashSet<urlLabel>();
            this.urls = new HashSet<url>();
            this.userCTags = new HashSet<userCTag>();
            this.userFTags = new HashSet<userFTag>();
        }
    
        public int Id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string dob { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<addressLabel> addressLabels { get; set; }
        public virtual ICollection<contact1> contacts { get; set; }
        public virtual ICollection<dateLabel> dateLabels { get; set; }
        public virtual ICollection<date> dates { get; set; }
        public virtual ICollection<email> emails { get; set; }
        public virtual ICollection<emailLabel> emailLabels { get; set; }
        public virtual ICollection<fTagDetail1> fTagDetails { get; set; }
        public virtual ICollection<mobileNo> mobileNoes { get; set; }
        public virtual ICollection<mobileNoLabel> mobileNoLabels { get; set; }
        public virtual ICollection<relativeName> relativeNames { get; set; }
        public virtual ICollection<relativeNameLabel> relativeNameLabels { get; set; }
        public virtual ICollection<socialProfile> socialProfiles { get; set; }
        public virtual ICollection<socialProfileLabel> socialProfileLabels { get; set; }
        public virtual ICollection<urlLabel> urlLabels { get; set; }
        public virtual ICollection<url> urls { get; set; }
        public virtual ICollection<userCTag> userCTags { get; set; }
        public virtual ICollection<userFTag> userFTags { get; set; }
    }
}
